# Generated by Django 4.2.1 on 2023-06-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_id_prog_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='value',
        ),
        migrations.AddField(
            model_name='rating',
            name='like',
            field=models.BooleanField(default=False, verbose_name='curtida'),
        ),
    ]
