# Generated by Django 4.2.1 on 2023-06-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matriculation',
            field=models.CharField(error_messages={'unique': 'Já existe um usuário com essa matrícula.'}, max_length=15, unique=True, verbose_name='matrícula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Já existe um usuário com esse nome.'}, max_length=40, unique=True, verbose_name='nome de usuário'),
        ),
    ]
